/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminalmini;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Priyang
 */
public class Insertcriminal extends javax.swing.JFrame {
        String crimetype="";
    /**
     * Creates new form Insertcriminal
     */
    public Insertcriminal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        criminaldetails3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        fulln = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        caadharnotext = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cphonenotext = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cidtext = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        chadresstext = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        cvdresstext = new javax.swing.JTextArea();
        ctype = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        casedetails1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        firnumbertext1 = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        crimedetailestext1 = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        vnametext1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        vadhaartext1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        vphonrtext2 = new javax.swing.JTextField();
        jScrollPane14 = new javax.swing.JScrollPane();
        casedetails2 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        offnametext = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        offaddress1 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        offid1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        offaadhartext = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoutb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 58, 147));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(214, 69, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criminalmini/criminalminipic1.png"))); // NOI18N
        jLabel1.setText("Mumbai Police Criminal Database");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("~");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        criminaldetails3.setBackground(new java.awt.Color(31, 58, 147));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(214, 69, 65));
        jLabel33.setText("Criminal Details");

        jLabel34.setForeground(new java.awt.Color(214, 69, 65));
        jLabel34.setText("Full Name*");

        fulln.setBackground(new java.awt.Color(232, 236, 241));
        fulln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnfirstnametextActionPerformed(evt);
            }
        });

        jLabel35.setForeground(new java.awt.Color(214, 69, 65));
        jLabel35.setText("Aaadhar No.*");

        caadharnotext.setBackground(new java.awt.Color(232, 236, 241));

        jLabel36.setForeground(new java.awt.Color(214, 69, 65));
        jLabel36.setText("Phone no.");

        cphonenotext.setBackground(new java.awt.Color(232, 236, 241));

        jLabel37.setForeground(new java.awt.Color(214, 69, 65));
        jLabel37.setText("Criminal ID*");

        cidtext.setBackground(new java.awt.Color(232, 236, 241));

        jLabel38.setForeground(new java.awt.Color(214, 69, 65));
        jLabel38.setText("Home Address");

        chadresstext.setBackground(new java.awt.Color(232, 236, 241));
        chadresstext.setColumns(20);
        chadresstext.setRows(5);
        jScrollPane10.setViewportView(chadresstext);

        jLabel39.setForeground(new java.awt.Color(214, 69, 65));
        jLabel39.setText("Village Address");

        cvdresstext.setBackground(new java.awt.Color(232, 236, 241));
        cvdresstext.setColumns(20);
        cvdresstext.setRows(5);
        jScrollPane11.setViewportView(cvdresstext);

        ctype.setBackground(new java.awt.Color(232, 236, 241));
        ctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thief", "Bank Thief", "Bank Loot", "Murderer", "Terrorist", "Rapist", "Fraud ", "Domestic Violence", " " }));
        ctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctypeActionPerformed(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(214, 69, 65));
        jLabel40.setText("Criminal Type*");

        javax.swing.GroupLayout criminaldetails3Layout = new javax.swing.GroupLayout(criminaldetails3);
        criminaldetails3.setLayout(criminaldetails3Layout);
        criminaldetails3Layout.setHorizontalGroup(
            criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminaldetails3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(criminaldetails3Layout.createSequentialGroup()
                        .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caadharnotext)
                            .addComponent(cidtext)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane11)
                            .addComponent(cphonenotext)
                            .addComponent(ctype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fulln))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        criminaldetails3Layout.setVerticalGroup(
            criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminaldetails3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fulln))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(caadharnotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cphonenotext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cidtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(13, 13, 13)
                .addGroup(criminaldetails3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criminaldetails3Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ctype))
                .addContainerGap())
        );

        jScrollPane9.setViewportView(criminaldetails3);

        casedetails1.setBackground(new java.awt.Color(31, 58, 147));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(214, 69, 65));
        jLabel42.setText("Case Details");

        jLabel43.setForeground(new java.awt.Color(214, 69, 65));
        jLabel43.setText("FIR Number*");

        jLabel44.setForeground(new java.awt.Color(214, 69, 65));
        jLabel44.setText("Crime Details*");

        firnumbertext1.setBackground(new java.awt.Color(232, 236, 241));
        firnumbertext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firnumbertext1ActionPerformed(evt);
            }
        });

        crimedetailestext1.setBackground(new java.awt.Color(232, 236, 241));
        crimedetailestext1.setColumns(20);
        crimedetailestext1.setRows(5);
        jScrollPane13.setViewportView(crimedetailestext1);

        jLabel45.setForeground(new java.awt.Color(214, 69, 65));
        jLabel45.setText("Victim Name*");

        vnametext1.setBackground(new java.awt.Color(232, 236, 241));
        vnametext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnametext1ActionPerformed(evt);
            }
        });

        jLabel46.setForeground(new java.awt.Color(214, 69, 65));
        jLabel46.setText("Victim Aaadhar No.*");

        vadhaartext1.setBackground(new java.awt.Color(232, 236, 241));
        vadhaartext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vadhaartext1ActionPerformed(evt);
            }
        });

        jLabel47.setForeground(new java.awt.Color(214, 69, 65));
        jLabel47.setText("Victim Phone no.");

        vphonrtext2.setBackground(new java.awt.Color(232, 236, 241));
        vphonrtext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vphonrtext2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout casedetails1Layout = new javax.swing.GroupLayout(casedetails1);
        casedetails1.setLayout(casedetails1Layout);
        casedetails1Layout.setHorizontalGroup(
            casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casedetails1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casedetails1Layout.createSequentialGroup()
                        .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addGap(52, 52, 52)
                        .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vadhaartext1)
                            .addComponent(vnametext1)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(firnumbertext1)
                            .addComponent(vphonrtext2)))
                    .addGroup(casedetails1Layout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41))
                    .addComponent(jLabel46))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        casedetails1Layout.setVerticalGroup(
            casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casedetails1Layout.createSequentialGroup()
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casedetails1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel41))
                    .addGroup(casedetails1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(firnumbertext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vnametext1)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(vadhaartext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(vphonrtext2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jScrollPane12.setViewportView(casedetails1);

        casedetails2.setBackground(new java.awt.Color(31, 58, 147));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(214, 69, 65));
        jLabel49.setText("Investigating Officer Details");

        jLabel50.setForeground(new java.awt.Color(214, 69, 65));
        jLabel50.setText("Officer Name*");

        jLabel51.setForeground(new java.awt.Color(214, 69, 65));
        jLabel51.setText("Officer Address");

        offnametext.setBackground(new java.awt.Color(232, 236, 241));
        offnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offnametextActionPerformed(evt);
            }
        });

        offaddress1.setBackground(new java.awt.Color(232, 236, 241));
        offaddress1.setColumns(20);
        offaddress1.setRows(5);
        jScrollPane15.setViewportView(offaddress1);

        jLabel52.setForeground(new java.awt.Color(214, 69, 65));
        jLabel52.setText("Officer ID*");

        offid1.setBackground(new java.awt.Color(232, 236, 241));
        offid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offid1ActionPerformed(evt);
            }
        });

        jLabel53.setForeground(new java.awt.Color(214, 69, 65));
        jLabel53.setText("Officer Aaadhar No.*");

        offaadhartext.setBackground(new java.awt.Color(232, 236, 241));
        offaadhartext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offaadhartextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout casedetails2Layout = new javax.swing.GroupLayout(casedetails2);
        casedetails2.setLayout(casedetails2Layout);
        casedetails2Layout.setHorizontalGroup(
            casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casedetails2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casedetails2Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48))
                    .addGroup(casedetails2Layout.createSequentialGroup()
                        .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(offaadhartext)
                            .addComponent(offid1)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(offnametext)))
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        casedetails2Layout.setVerticalGroup(
            casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casedetails2Layout.createSequentialGroup()
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casedetails2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel48))
                    .addGroup(casedetails2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(offnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offid1)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(casedetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(offaadhartext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jScrollPane14.setViewportView(casedetails2);

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        logoutb.setText("Logout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoutb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(submitbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(logoutb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitbutton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(JFrame.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void fullnfirstnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnfirstnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnfirstnametextActionPerformed

    private void firnumbertext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firnumbertext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firnumbertext1ActionPerformed

    private void vnametext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnametext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnametext1ActionPerformed

    private void vadhaartext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vadhaartext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vadhaartext1ActionPerformed

    private void vphonrtext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vphonrtext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vphonrtext2ActionPerformed

    private void offnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offnametextActionPerformed

    private void offid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offid1ActionPerformed

    private void offaadhartextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offaadhartextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offaadhartextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Operationpage o=new Operationpage();
        o.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
         String cfname,vname,offname,cid,chaddress,cvaddress,caadhar,cphone,firno,crimedata,vaadhar,vphone,offaddress,offid,offaadhar;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/criminalmini?zeroDateTimeBehavior=convertToNull","root","");
            Statement st =(Statement) con.createStatement();
            if(fulln.equals("") || caadharnotext.equals("")||crimetype.equals("")||cidtext.equals("")|| firnumbertext1.equals("") || crimedetailestext1.equals("")||vnametext1.equals("")|| vadhaartext1.equals("") || offnametext.equals("") || offid1.equals("")||offaadhartext.equals("")) {
              JOptionPane.showMessageDialog(null,"Necessary Details Incomplete");                  
           } else {
                String cal,val,ial;
                cfname=fulln.getText();
                caadhar=caadharnotext.getText();
                cphone=cphonenotext.getText();
                cid=cidtext.getText();
                chaddress=chadresstext.getText();
                 cvaddress=cvdresstext.getText();
                 firno=firnumbertext1.getText();
                 crimedata=crimedetailestext1.getText();
                 vname=vnametext1.getText();
                 vaadhar=vadhaartext1.getText();
                 vphone=vphonrtext2.getText();
                 offname=offnametext.getText();
                 offaddress=offaddress1.getText();
                 offid=offid1.getText();
                 offaadhar=offaadhartext.getText();
cal="INSERT INTO criminaldetails(fullname,aadharno,phoneno,criminalid,homeaddress,villageaddress,criminaltype) VALUES ('"+cfname+"','"+caadhar+"','"+cphone+"','"+cid+"','"+chaddress+"','"+cvaddress+"','"+crimetype+"')";    
val="INSERT INTO casedetail(firno,crimedetails,vicname,vicaadhar,vicphoneno,criminalid) VALUES ('"+firno+"','"+crimedata+"','"+vname+"','"+vaadhar+"','"+vphone+"','"+cid+"')";      
ial="INSERT INTO `investigatingofficer`(`offname`, `offaddress`, `offid`, `offaadhar`, `criminalid`) VALUES ('"+offname+"','"+offaddress+"','"+offid+"','"+offaadhar+"','"+cid+"')";
 st.executeUpdate(cal);
 st.executeUpdate(val);
 st.executeUpdate(ial);
                JOptionPane.showMessageDialog(null,"Data Insertion Successful");
                st.close();
                con.close();
            }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void ctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctypeActionPerformed
        crimetype=ctype.getSelectedItem().toString();
    }//GEN-LAST:event_ctypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertcriminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertcriminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caadharnotext;
    private javax.swing.JPanel casedetails1;
    private javax.swing.JPanel casedetails2;
    private javax.swing.JTextArea chadresstext;
    private javax.swing.JTextField cidtext;
    private javax.swing.JTextField cphonenotext;
    private javax.swing.JTextArea crimedetailestext1;
    private javax.swing.JPanel criminaldetails3;
    private javax.swing.JComboBox<String> ctype;
    private javax.swing.JTextArea cvdresstext;
    private javax.swing.JTextField firnumbertext1;
    private javax.swing.JTextField fulln;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton logoutb;
    private javax.swing.JTextField offaadhartext;
    private javax.swing.JTextArea offaddress1;
    private javax.swing.JTextField offid1;
    private javax.swing.JTextField offnametext;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField vadhaartext1;
    private javax.swing.JTextField vnametext1;
    private javax.swing.JTextField vphonrtext2;
    // End of variables declaration//GEN-END:variables
}
