/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminalmini;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Priyang
 */
public class SearchandDelete extends javax.swing.JFrame {
public static String userrole,nameid;
    /**
     * Creates new form SearchandDelete
     */
    public SearchandDelete() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchtext = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        searchdeletebutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoutb = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(214, 69, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criminalmini/criminalminipic1.png"))); // NOI18N
        jLabel1.setText("Mumbai Police Criminal Database");

        jPanel1.setBackground(new java.awt.Color(31, 58, 147));

        searchtext.setBackground(new java.awt.Color(232, 236, 241));
        searchtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchtext.setText("Enter Criminal Name Or ID");

        searchbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        searchdeletebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchdeletebutton.setText("Search And Delete");
        searchdeletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdeletebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchtext)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(searchdeletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchdeletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        logoutb.setText("Logout");
        logoutb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("~");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logoutb)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutb))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Operationpage o=new Operationpage();
        o.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchdeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdeletebuttonActionPerformed
       String s,r="",m="",q,p,b;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/criminalmini?zeroDateTimeBehavior=convertToNull","root","");
            Statement st =(Statement) con.createStatement();
            PreparedStatement  pt = con.prepareStatement("select fullname,criminalid from criminaldetails where fullname like ? or criminalid like ?");
            s=searchtext.getText();
            if(userrole.equalsIgnoreCase("Low level officer"))
            {
                JOptionPane.showMessageDialog(null,"Access Denied"); 
            }
            else{
            if(s.equals("") || s.equalsIgnoreCase("Enter criminal name or id"))
            {
              JOptionPane.showMessageDialog(null,"Invalid data");  
            }
            else
            {
              pt.setString(1, s);
              pt.setString(2,s);
               ResultSet rs = pt.executeQuery();
                while (rs.next()) {
                    r=rs.getString(1);
                    m=rs.getString(2);
                }
                if(!s.equals(r) && !s.equals(m))
                {
                 JOptionPane.showMessageDialog(null,"Criminal not found");     
                }
                else if(s.equals(r) && userrole.equalsIgnoreCase("Admin Level Officer"))
                {
                 q="DELETE FROM `criminaldetails` WHERE fullname like '"+s+"';";
                 p="DELETE FROM `casedetail` WHERE criminalid like '"+m+"';";
                 b="DELETE FROM `investigatingofficer` WHERE criminalid like '"+m+"';";
                 st.executeUpdate(q);
                 st.executeUpdate(p);
                 st.executeUpdate(b);
                  JOptionPane.showMessageDialog(null,"Criminal Successfully Deleted");  
                }
                else if(s.equals(m)&& userrole.equalsIgnoreCase("Admin Level Officer"))
                {
                 q="DELETE FROM `criminaldetails` WHERE criminalid like '"+s+"';";
                 p="DELETE FROM `casedetail` WHERE criminalid like '"+m+"';";
                 b="DELETE FROM `investigatingofficer` WHERE criminalid like '"+m+"';";
                 st.executeUpdate(q);
                  st.executeUpdate(p);
                 st.executeUpdate(b);
                  JOptionPane.showMessageDialog(null,"CriminalData Successfully Deleted");  
                }
                 else if(s.equals(r) && !userrole.equalsIgnoreCase("Admin Level Officer"))
                {
                 q="DELETE FROM `noterror` WHERE fullname like '"+s+"';";
                 p="DELETE FROM `casedetail` WHERE criminalid like '"+m+"';";
                 b="DELETE FROM `investigatingofficer` WHERE criminalid like '"+m+"';";
                 st.executeUpdate(q);
                 st.executeUpdate(p);
                 st.executeUpdate(b);
                  JOptionPane.showMessageDialog(null,"Criminal Successfully Deleted");  
                }
                else if(s.equals(m)&& !userrole.equalsIgnoreCase("Admin Level Officer"))
                {
                 q="DELETE FROM `noterror` WHERE criminalid like '"+s+"';";
                 p="DELETE FROM `casedetail` WHERE criminalid like '"+m+"';";
                 b="DELETE FROM `investigatingofficer` WHERE criminalid like '"+m+"';";
                 st.executeUpdate(q);
                  st.executeUpdate(p);
                 st.executeUpdate(b);
                  JOptionPane.showMessageDialog(null,"CriminalData Successfully Deleted"); 
               
                } 
            }
            }
            st.close();
            pt.close();
            con.close();
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_searchdeletebuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        String p,q="",m="";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/criminalmini?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement  pt = con.prepareStatement("select fullname,criminalid from criminaldetails where fullname like ? or criminalid like ?");
             PreparedStatement  pt1 = con.prepareStatement("select fullname,criminalid from noterror where fullname like ? or criminalid like ?");
            p=searchtext.getText();
            if(userrole.equalsIgnoreCase("Low level officer"))
            {
                if(p.equals("") || p.equalsIgnoreCase("Enter criminal name or id"))
            {
              JOptionPane.showMessageDialog(null,"Invalid data");  
            }
            else
            {
              pt1.setString(1, p);
              pt1.setString(2,p);
               ResultSet rs = pt1.executeQuery();
                while (rs.next()) {
                    q=rs.getString(1);
                    m=rs.getString(2);
                }
                if(!p.equals(q) && !p.equals(m))
                {
                 JOptionPane.showMessageDialog(null,"Criminal not found");     
                }
                else
                {
                  nameid=p;
                  detailspage.name = p;
                  detailspage d=new detailspage();
                  d.setVisible(true);
                        this.dispose();
                }
        }
            }
            else{
            if(p.equals("") || p.equalsIgnoreCase("Enter criminal name or id"))
            {
              JOptionPane.showMessageDialog(null,"Invalid data");  
            }
            else
            {
              pt.setString(1, p);
              pt.setString(2,p);
               ResultSet rs = pt.executeQuery();
                while (rs.next()) {
                    q=rs.getString(1);
                    m=rs.getString(2);
                }
                if(!p.equals(q) && !p.equals(m))
                {
                 JOptionPane.showMessageDialog(null,"Criminal not found");     
                }
                else
                {
                  nameid=p;
                  detailspage.name = p;
                  detailspage d=new detailspage();
                  d.setVisible(true);
                        this.dispose();
                }
        }
    }
        }
        catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void logoutbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchandDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchandDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchandDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchandDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchandDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutb;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton searchdeletebutton;
    private javax.swing.JTextField searchtext;
    // End of variables declaration//GEN-END:variables
}
